### ISSUE TITLE
Install for compute nodes? 

### ISSUE THREAD

**Issue by surak** [marvel-nccr/ansible-role-slurm#12]
This installs a slurm controller, which is great - what about the configuration for the compute nodes?

**Comment by ltalirz** [comment]
Hey @surak - this role is used in a virtual machine, where so far the assumption was that the compute node *is* the virtual machine (therefore the role contains e.g. some autodetection capability around the CPUs on the VM).

So far the role was not yet destined to set up a compute cluster with multiple nodes - there are tools like https://github.com/elasticluster/elasticluster for this

If you're just thinking of a small modification however that would support your use case, feel free to make a pull request

**Comment by surak** [comment]
I will probably do, but for now, it would be good to clarify that in the README, what do you think?

**Comment by ltalirz** [comment]
thanks for the suggestion; done in 60ccf32b02f32f0042cc89bb2cbce336550ddef3
