### ISSUE TITLE
Make set hostname configurable

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/ansible-role-slurm#7]
this was raised by @adegomme 

<details>
<summary>
Original issue
</summary>
 I ran again from a new and clean quantum-mobile develop repo the defaults steps and got the same error on the vagrant up one.

TASK [marvel-nccr.slurm : do test submission] **********************************
fatal: [default]: FAILED! => changed=true 
 cmd:
 - /tmp/slurm-tests/test-submit.sh
 delta: '0:00:29.139083'
 end: '2020-06-30 15:12:38.055332'
 msg: non-zero return code
 rc: 1
 start: '2020-06-30 15:12:08.916249'
 stderr: 'sbatch: error: Batch job submission failed: Unable to contact slurm controller (connect failure)'
 stderr_lines:
 - 'sbatch: error: Batch job submission failed: Unable to contact slurm controller (connect failure)'
 stdout: 'Writing to folder: /tmp/slurm-tests/test1'
 stdout_lines: <omitted> 

when I connect to the vm through ssh, I get the same " Unable to contact slurm controller" at every single slurm command attempt, like sinfo... restarting both slurmd and slurmctld services does not seem to help, they are running (but slurmd logs reports a lot of this same issue, once every 30s).
</details>

Then over email there was some discussion 

> the issue seemed to be that "qmobile" is indeed not understood as being localhost, and the slurm requests went to my ISP.  I added "127.0.0.1 qmobile" entry in /etc/hosts to force the match and rebooted the instance. It is now proceeding the rest of the build. But maybe this should be added to the steps ?

> Essentially, you need to find the ‘current’ IP and change the hostname, in an automated way

>  I don’t think using 127.0.0.1 works. You really need to specify a name (and not an IP) and the name CANNOT point to a local loopback but must be an ip different than 127.*.*.*

As @giovannipizzi pointed out, a "fix" for this is already in the tasks, but only used for docker builds: 

https://github.com/marvel-nccr/ansible-role-slurm/blob/e0451c758508937e2b581e9bb11e2d5fff66f144/tasks/hostname.yml#L9-L16

I guess we can just change:

https://github.com/marvel-nccr/ansible-role-slurm/blob/e0451c758508937e2b581e9bb11e2d5fff66f144/tasks/hostname.yml#L16

to 

```yaml
  when: slurm_set_hostname or (cloud_platform is defined and cloud_platform == 'docker')
```

and add `slurm_set_hostname: false` which the user can then change

@adegomme out of interest, what system were you building on where this occurred?

**Comment by ltalirz** [comment]
While the current task works in ubuntu docker images, I think the line (172.XXX.... ) is docker-specific and will not be present in general on Ubuntu machines (e.g. it is *not* present in the tutorial VMs).

You may need to adapt the line for these cases

Output on tutorial VM:
```
$ cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
127.0.1.1 localhost
```

**Comment by chrisjsewell** [comment]
ah yeh I missed that it was 172 not 127!
So just this task again, but with 127.0.0.1, or a less specific regex?

**Comment by ltalirz** [comment]
That might be it - I'm not very familiar with which loopback one should be setting here.

It means the role will change the hostname of the virtual or physical VM, though, i.e. some kind of warning might be appropriate when this option is selected.

Perhaps the better solution overall would be to detect the hostname an simply use that in the slurm configuration?
In principle, changing the hostname should not be the task of the slurm role.

@giovannipizzi If one uses the hostname of the machine in the slurm configuration, does one still need to add something to /etc/hosts to make it work?
